graph TD
    A(Requirements<br>Gathering)
    B(Design the<br>Requirements)
    C(Construction/<br>Iteration)
    D(Testing/Quality<br>Assurance)
    E(Deployment)
    F(Feedback)

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> A

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "F": {
%%       "x": -10.0,
%%       "y": 150.0
%%     },
%%     "D": {
%%       "x": 210.0,
%%       "y": 260.0
%%     },
%%     "B": {
%%       "x": 450.0,
%%       "y": 150.0
%%     },
%%     "C": {
%%       "x": 450.0,
%%       "y": 260.0
%%     },
%%     "E": {
%%       "x": -10.0,
%%       "y": 260.0
%%     }
%%   },
%%   "edges": {},
%%   "node_styles": {
%%     "E": {
%%       "fill": "#E9E0C9",
%%       "stroke": "#none"
%%     },
%%     "B": {
%%       "fill": "#D4EAC8",
%%       "stroke": "#none"
%%     },
%%     "F": {
%%       "fill": "#E6C2C2",
%%       "stroke": "#none"
%%     },
%%     "D": {
%%       "fill": "#EBCDE5",
%%       "stroke": "#none"
%%     },
%%     "A": {
%%       "fill": "#FFDAC1",
%%       "stroke": "#none"
%%     },
%%     "C": {
%%       "fill": "#C4D9E9",
%%       "stroke": "#none"
%%     }
%%   },
%%   "edge_styles": {}
%% }
%% OXDRAW LAYOUT END
