graph TD
    A[Select experts] --> B[Initial criteria]
    B --> C[Design and distribute questionnaires]
    C --> D[Recover and modify questionnaires]
    D --> E{Consensus}
    E -- No --> D
    E -- Yes --> F[Obtain the criteria]

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "A": {
%%       "x": 200.0,
%%       "y": 100.0
%%     },
%%     "B": {
%%       "x": 200.0,
%%       "y": 180.0
%%     },
%%     "C": {
%%       "x": 200.0,
%%       "y": 260.0
%%     },
%%     "D": {
%%       "x": 200.0,
%%       "y": 340.0
%%     },
%%     "E": {
%%       "x": 200.0,
%%       "y": 420.0
%%     },
%%     "F": {
%%       "x": 200.0,
%%       "y": 540.0
%%     }
%%   },
%%   "edges": {
%%     "E --> D": {
%%       "points": [
%%         {
%%           "x": 400.0,
%%           "y": 420.0
%%         },
%%         {
%%           "x": 400.0,
%%           "y": 380.0
%%         },
%%         {
%%           "x": 400.0,
%%           "y": 340.0
%%         }
%%       ]
%%     },
%%     "D --> E": {
%%       "points": [
%%         {
%%           "x": 200.0,
%%           "y": 390.0
%%         }
%%       ]
%%     },
%%     "E --> F": {
%%       "points": [
%%         {
%%           "x": 200.0,
%%           "y": 475.0
%%         }
%%       ]
%%     }
%%   },
%%   "node_styles": {},
%%   "edge_styles": {}
%% }
%% OXDRAW LAYOUT END
