graph TD
  %% app(Application)
  osrm(OSRM)
  lrm(Leaflet Routing Machine)
  ll(Leaflet.js)
  tiles(Map Tiles)

  ll --> |request| tiles
  tiles --> |response| ll

  ll --> |input| lrm
  lrm --> |coords| osrm

  osrm --> |coords| lrm
  lrm --> |route| ll

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "lrm": {
%%       "x": 240.0,
%%       "y": 250.0
%%     },
%%     "tiles": {
%%       "x": 500.0,
%%       "y": 440.0
%%     },
%%     "osrm": {
%%       "x": 240.0,
%%       "y": 60.0
%%     },
%%     "ll": {
%%       "x": 240.0,
%%       "y": 440.0
%%     }
%%   },
%%   "edges": {},
%%   "node_styles": {},
%%   "edge_styles": {}
%% }
%% OXDRAW LAYOUT END
