graph TD
A[Requirements]
B[Design]
C[Development]
D[Testing]
E[Deployment]
F[Maintenance]

A --> B
B --> C
C --> D
D --> E
E --> F
F --> A

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "C": {
%%       "x": 388.0,
%%       "y": 270.0
%%     },
%%     "A": {
%%       "x": 100.0,
%%       "y": 140.0
%%     },
%%     "E": {
%%       "x": 680.0,
%%       "y": 400.0
%%     },
%%     "F": {
%%       "x": 830.0,
%%       "y": 470.0
%%     },
%%     "D": {
%%       "x": 530.0,
%%       "y": 340.0
%%     },
%%     "B": {
%%       "x": 250.0,
%%       "y": 200.0
%%     }
%%   },
%%   "edges": {
%%     "E --> F": {
%%       "points": [
%%         {
%%           "x": 830.0,
%%           "y": 400.0
%%         }
%%       ]
%%     },
%%     "B --> C": {
%%       "points": [
%%         {
%%           "x": 390.0,
%%           "y": 200.0
%%         }
%%       ]
%%     },
%%     "F --> A": {
%%       "points": [
%%         {
%%           "x": 100.0,
%%           "y": 470.0
%%         }
%%       ]
%%     },
%%     "C --> D": {
%%       "points": [
%%         {
%%           "x": 530.0,
%%           "y": 270.0
%%         }
%%       ]
%%     },
%%     "A --> B": {
%%       "points": [
%%         {
%%           "x": 250.0,
%%           "y": 140.0
%%         }
%%       ]
%%     },
%%     "D --> E": {
%%       "points": [
%%         {
%%           "x": 680.7,
%%           "y": 340.0
%%         }
%%       ]
%%     }
%%   },
%%   "node_styles": {
%%     "C": {
%%       "fill": "#C4D9E9",
%%       "stroke": "#none"
%%     },
%%     "A": {
%%       "fill": "#FFDAC1",
%%       "stroke": "#none"
%%     },
%%     "D": {
%%       "fill": "#EBCDE5",
%%       "stroke": "#none"
%%     },
%%     "B": {
%%       "fill": "#D4EAC8",
%%       "stroke": "#none"
%%     },
%%     "E": {
%%       "fill": "#E9E0C9",
%%       "stroke": "#none"
%%     },
%%     "F": {
%%       "fill": "#E6C2C2",
%%       "stroke": "#none"
%%     }
%%   },
%%   "edge_styles": {}
%% }
%% OXDRAW LAYOUT END
